// <auto-generated />
using System;
using ElectronicMaps.Infrastructure.Persistence.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicMaps.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220235652_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindowsIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WindowsIdentity")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentFamilyId");

                    b.HasIndex("FormTypeId");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyFormTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyFormTypeId");

                    b.ToTable("ComponentFamilies", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamilyRemark", b =>
                {
                    b.Property<int>("ComponentFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemarkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComponentFamilyId", "RemarkId");

                    b.HasIndex("RemarkId");

                    b.ToTable("ComponentFamilyRemark");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentRemark", b =>
                {
                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemarkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComponentId", "RemarkId");

                    b.HasIndex("RemarkId");

                    b.ToTable("ComponentRemark");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.FormType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FormTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 68,
                            Code = "FORM_68",
                            DisplayName = "Форма 68"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FORM_4",
                            DisplayName = "Форма 4"
                        });
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FormTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormTypeId");

                    b.ToTable("ParameterDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DcVoltage",
                            DisplayName = "Постоянное напряжение",
                            FormTypeId = 68,
                            Order = 1,
                            Unit = "В",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 2,
                            Code = "AcVoltage",
                            DisplayName = "Переменное напряжение",
                            FormTypeId = 68,
                            Order = 2,
                            Unit = "В",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 3,
                            Code = "ImpulseVoltage",
                            DisplayName = "Импульсное напряжение",
                            FormTypeId = 68,
                            Order = 3,
                            Unit = "В",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "SumVoltage",
                            DisplayName = "Суммарное напряжение",
                            FormTypeId = 68,
                            Order = 4,
                            Unit = "В",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "Frequancy",
                            DisplayName = "Частота",
                            FormTypeId = 68,
                            Order = 5,
                            Unit = "Гц",
                            ValueKind = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "ImpulseDuration",
                            DisplayName = "Длительность импульса",
                            FormTypeId = 68,
                            Order = 6,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "ImpulsePower",
                            DisplayName = "Импульсная мощность",
                            FormTypeId = 68,
                            Order = 7,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 8,
                            Code = "MeanPower",
                            DisplayName = "Средняя мощность",
                            FormTypeId = 68,
                            Order = 8,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 9,
                            Code = "LoadKoeffImpulse",
                            DisplayName = "Коэффициент нагрузки (импульсный режим)",
                            FormTypeId = 68,
                            Order = 9,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 10,
                            Code = "CurrentMovingContact",
                            DisplayName = "Ток через подвижный контакт",
                            FormTypeId = 68,
                            Order = 10,
                            Unit = "А",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 11,
                            Code = "AmbientTemperature",
                            DisplayName = "Температура окружающей среды",
                            FormTypeId = 68,
                            Order = 11,
                            Unit = "°C",
                            ValueKind = 2
                        },
                        new
                        {
                            Id = 12,
                            Code = "SuperHeatTemperature",
                            DisplayName = "Температура перегрева",
                            FormTypeId = 68,
                            Order = 12,
                            Unit = "°C",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 13,
                            Code = "SumPower",
                            DisplayName = "Суммарная мощность",
                            FormTypeId = 68,
                            Order = 13,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 14,
                            Code = "AmbientTemperatureCase",
                            DisplayName = "Температура корпуса",
                            FormTypeId = 68,
                            Order = 14,
                            Unit = "°C",
                            ValueKind = 2
                        },
                        new
                        {
                            Id = 15,
                            Code = "LoadKoeff",
                            DisplayName = "Коэффициент нагрузки",
                            FormTypeId = 68,
                            Order = 15,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 16,
                            Code = "InListTTZ",
                            DisplayName = "Наличие в перечнях при утверждении ТТЗ",
                            FormTypeId = 4,
                            Order = 1,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 17,
                            Code = "LastEditions",
                            DisplayName = "Наличие в перечнях последних редакций",
                            FormTypeId = 4,
                            Order = 2,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 18,
                            Code = "ResourceHours",
                            DisplayName = "Показатель ресурса, ч",
                            FormTypeId = 4,
                            Order = 3,
                            Unit = "ч",
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 19,
                            Code = "LifeTimeYears",
                            DisplayName = "Показатель срока службы, лет",
                            FormTypeId = 4,
                            Order = 4,
                            Unit = "лет",
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 20,
                            Code = "PreservationYears",
                            DisplayName = "Показатель сохраняемости, лет",
                            FormTypeId = 4,
                            Order = 5,
                            Unit = "лет",
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 21,
                            Code = "FrequencyRange",
                            DisplayName = "Диапазон частот, Гц",
                            FormTypeId = 4,
                            Order = 6,
                            Unit = "Гц",
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 22,
                            Code = "SoundPressure",
                            DisplayName = "Уровень звукового давления, дБ",
                            FormTypeId = 4,
                            Order = 7,
                            Unit = "дБ",
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 23,
                            Code = "LineAcceleration",
                            DisplayName = "Линейное ускорение, м·с⁻² (G)",
                            FormTypeId = 4,
                            Order = 8,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 24,
                            Code = "LowPressure",
                            DisplayName = "Давление окр. среды пониженное",
                            FormTypeId = 4,
                            Order = 9,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 25,
                            Code = "HighPressure",
                            DisplayName = "Давление окр. среды повышенное",
                            FormTypeId = 4,
                            Order = 10,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 26,
                            Code = "LowTemperature",
                            DisplayName = "Предельная температура пониженная, °C",
                            FormTypeId = 4,
                            Order = 11,
                            Unit = "°C",
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 27,
                            Code = "HighTemperature",
                            DisplayName = "Предельная температура повышенная, °C",
                            FormTypeId = 4,
                            Order = 12,
                            Unit = "°C",
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 28,
                            Code = "HumidityPercent",
                            DisplayName = "Относительная влажность, %",
                            FormTypeId = 4,
                            Order = 13,
                            Unit = "%",
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 29,
                            Code = "HumidityCelcius",
                            DisplayName = "Температура при заданной влажности, °C",
                            FormTypeId = 4,
                            Order = 14,
                            Unit = "°C",
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 30,
                            Code = "Dew",
                            DisplayName = "Роса, иней",
                            FormTypeId = 4,
                            Order = 15,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 31,
                            Code = "SpecialFactors",
                            DisplayName = "Стойкость к ВССФ",
                            FormTypeId = 4,
                            Order = 16,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 32,
                            Code = "Note",
                            DisplayName = "Примечание",
                            FormTypeId = 4,
                            Order = 17,
                            ValueKind = 1
                        });
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pins")
                        .HasColumnType("TEXT");

                    b.Property<string>("StringValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentFamilyId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ParameterDefinitionId");

                    b.ToTable("ParameterValues", null, t =>
                        {
                            t.HasCheckConstraint("CK_ParameterValues_Target", "(([ComponentId] IS NOT NULL AND [ComponentFamilyId] IS NULL) OR ([ComponentId] IS NULL AND [ComponentFamilyId] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Remark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("Remark");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Component", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.ComponentFamily", "ComponentFamily")
                        .WithMany("Components")
                        .HasForeignKey("ComponentFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicMaps.Domain.Entities.FormType", "FormType")
                        .WithMany()
                        .HasForeignKey("FormTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponentFamily");

                    b.Navigation("FormType");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamily", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.FormType", "FamilyFormType")
                        .WithMany()
                        .HasForeignKey("FamilyFormTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamilyFormType");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamilyRemark", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.ComponentFamily", "ComponentFamily")
                        .WithMany()
                        .HasForeignKey("ComponentFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicMaps.Domain.Entities.Remark", "Remark")
                        .WithMany("Families")
                        .HasForeignKey("RemarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentFamily");

                    b.Navigation("Remark");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentRemark", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicMaps.Domain.Entities.Remark", "Remark")
                        .WithMany("Components")
                        .HasForeignKey("RemarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Remark");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterDefinition", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.FormType", "FormType")
                        .WithMany("Parameters")
                        .HasForeignKey("FormTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormType");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterValue", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.ComponentFamily", "ComponentFamily")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ComponentFamilyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectronicMaps.Domain.Entities.Component", "Component")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicMaps.Domain.Entities.ParameterDefinition", "ParameterDefinition")
                        .WithMany()
                        .HasForeignKey("ParameterDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("ComponentFamily");

                    b.Navigation("ParameterDefinition");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Component", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamily", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.FormType", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Remark", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Families");
                });
#pragma warning restore 612, 618
        }
    }
}
