// <auto-generated />
using System;
using ElectronicMaps.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicMaps.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124201737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    b.HasIndex("ComponentFamilyId");

                    b.HasIndex("Name");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyFormCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentFamilies", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.FormType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FormTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FORM_RESISTOR",
                            DisplayName = "Форма резистора",
                            Scope = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "FORM_CHIP",
                            DisplayName = "Форма микросхемы",
                            Scope = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "FORM_64",
                            DisplayName = "Форма 64",
                            Scope = 1
                        });
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FormTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormTypeId");

                    b.ToTable("ParameterDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DcVoltage",
                            DisplayName = "Постоянное напряжение",
                            FormTypeId = 1,
                            Order = 1,
                            Unit = "В",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 2,
                            Code = "AcVoltage",
                            DisplayName = "Переменное напряжение",
                            FormTypeId = 1,
                            Order = 2,
                            Unit = "В",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 3,
                            Code = "ImpulseVoltage",
                            DisplayName = "Импульсное напряжение",
                            FormTypeId = 1,
                            Order = 3,
                            Unit = "В",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "SumVoltage",
                            DisplayName = "Суммарное напряжение",
                            FormTypeId = 1,
                            Order = 4,
                            Unit = "В",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "Frequancy",
                            DisplayName = "Частота",
                            FormTypeId = 1,
                            Order = 5,
                            Unit = "Гц",
                            ValueKind = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "ImpulseDuration",
                            DisplayName = "Длительность импульса",
                            FormTypeId = 1,
                            Order = 6,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "ImpulsePower",
                            DisplayName = "Импульсная мощность",
                            FormTypeId = 1,
                            Order = 7,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 8,
                            Code = "MeanPower",
                            DisplayName = "Средняя мощность",
                            FormTypeId = 1,
                            Order = 8,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 9,
                            Code = "LoadKoeffImpulse",
                            DisplayName = "Коэффициент нагрузки (импульс)",
                            FormTypeId = 1,
                            Order = 9,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 10,
                            Code = "CurrentMovingContact",
                            DisplayName = "Ток через подвижный контакт",
                            FormTypeId = 1,
                            Order = 10,
                            Unit = "А",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 11,
                            Code = "AmbientTemperature",
                            DisplayName = "Температура окружающей среды",
                            FormTypeId = 1,
                            Order = 11,
                            Unit = "°C",
                            ValueKind = 2
                        },
                        new
                        {
                            Id = 12,
                            Code = "SuperHeatTemperature",
                            DisplayName = "Температура перегрева",
                            FormTypeId = 1,
                            Order = 12,
                            Unit = "°C",
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 13,
                            Code = "SumPower",
                            DisplayName = "Суммарная мощность",
                            FormTypeId = 1,
                            Order = 13,
                            ValueKind = 3
                        },
                        new
                        {
                            Id = 14,
                            Code = "AmbientTemperatureCase",
                            DisplayName = "Температура корпуса",
                            FormTypeId = 1,
                            Order = 14,
                            Unit = "°C",
                            ValueKind = 2
                        },
                        new
                        {
                            Id = 15,
                            Code = "LoadKoeff",
                            DisplayName = "Коэффициент нагрузки",
                            FormTypeId = 1,
                            Order = 15,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 16,
                            Code = "SupplayVoltage",
                            DisplayName = "Напряжение питания",
                            FormTypeId = 2,
                            Order = 1,
                            Unit = "В",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 17,
                            Code = "SupplyOrder",
                            DisplayName = "Порядок подачи напряжения питания",
                            FormTypeId = 2,
                            Order = 2,
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 18,
                            Code = "LowLevelVolatge",
                            DisplayName = "Напряжение низкого уровня",
                            FormTypeId = 2,
                            Order = 3,
                            Unit = "В",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 19,
                            Code = "HighLevelVolatge",
                            DisplayName = "Напряжение высокого уровня",
                            FormTypeId = 2,
                            Order = 4,
                            Unit = "В",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 20,
                            Code = "ImpulseDuration",
                            DisplayName = "Длительность импульса",
                            FormTypeId = 2,
                            Order = 5,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 21,
                            Code = "TurnOnTrasnsition",
                            DisplayName = "Время перехода при включении",
                            FormTypeId = 2,
                            Order = 6,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 22,
                            Code = "TurnOffTransition",
                            DisplayName = "Время перехода при выключении",
                            FormTypeId = 2,
                            Order = 7,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 23,
                            Code = "Frequency",
                            DisplayName = "Частота",
                            FormTypeId = 2,
                            Order = 8,
                            Unit = "МГц",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 24,
                            Code = "Timet1",
                            DisplayName = "Время t1",
                            FormTypeId = 2,
                            Order = 9,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 25,
                            Code = "Timet2",
                            DisplayName = "Время t2",
                            FormTypeId = 2,
                            Order = 10,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 26,
                            Code = "OutCurrentLowLevel",
                            DisplayName = "Выходной ток низкого уровня",
                            FormTypeId = 2,
                            Order = 11,
                            Unit = "мА",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 27,
                            Code = "OutCurrentHighLevel",
                            DisplayName = "Выходной ток высокого уровня",
                            FormTypeId = 2,
                            Order = 12,
                            Unit = "мА",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 28,
                            Code = "CapacityLoad",
                            DisplayName = "Ёмкость нагрузки",
                            FormTypeId = 2,
                            Order = 13,
                            Unit = "пФ",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 29,
                            Code = "PowerDissipation",
                            DisplayName = "Мощность рассеивания",
                            FormTypeId = 2,
                            Order = 14,
                            Unit = "мВт",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 30,
                            Code = "PosName",
                            DisplayName = "Позиционное обозначение и номера выводов",
                            FormTypeId = 2,
                            Order = 15,
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 31,
                            Code = "AmbientTemperatureCase",
                            DisplayName = "Температура корпуса",
                            FormTypeId = 2,
                            Order = 16,
                            Unit = "°C",
                            ValueKind = 2
                        },
                        new
                        {
                            Id = 32,
                            Code = "LoadKoeff",
                            DisplayName = "Коэффициент нагрузки",
                            FormTypeId = 2,
                            Order = 17,
                            ValueKind = 1
                        },
                        new
                        {
                            Id = 33,
                            Code = "SupplayVoltage",
                            DisplayName = "Напряжение питания",
                            FormTypeId = 3,
                            Order = 1,
                            Unit = "В",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 34,
                            Code = "SupplyOrder",
                            DisplayName = "Порядок подачи напряжения питания",
                            FormTypeId = 3,
                            Order = 2,
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 35,
                            Code = "LowLevelVolatge",
                            DisplayName = "Напряжение низкого уровня",
                            FormTypeId = 3,
                            Order = 3,
                            Unit = "В",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 36,
                            Code = "HighLevelVolatge",
                            DisplayName = "Напряжение высокого уровня",
                            FormTypeId = 3,
                            Order = 4,
                            Unit = "В",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 37,
                            Code = "ImpulseDuration",
                            DisplayName = "Длительность импульса",
                            FormTypeId = 3,
                            Order = 5,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 38,
                            Code = "TurnOnTrasnsition",
                            DisplayName = "Время перехода при включении",
                            FormTypeId = 3,
                            Order = 6,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 39,
                            Code = "TurnOffTransition",
                            DisplayName = "Время перехода при выключении",
                            FormTypeId = 3,
                            Order = 7,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 40,
                            Code = "Frequency",
                            DisplayName = "Частота",
                            FormTypeId = 3,
                            Order = 8,
                            Unit = "МГц",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 41,
                            Code = "Timet1",
                            DisplayName = "Время t1",
                            FormTypeId = 3,
                            Order = 9,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 42,
                            Code = "Timet2",
                            DisplayName = "Время t2",
                            FormTypeId = 3,
                            Order = 10,
                            Unit = "нс",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 43,
                            Code = "OutCurrentLowLevel",
                            DisplayName = "Выходной ток низкого уровня",
                            FormTypeId = 3,
                            Order = 11,
                            Unit = "мА",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 44,
                            Code = "OutCurrentHighLevel",
                            DisplayName = "Выходной ток высокого уровня",
                            FormTypeId = 3,
                            Order = 12,
                            Unit = "мА",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 45,
                            Code = "CapacityLoad",
                            DisplayName = "Ёмкость нагрузки",
                            FormTypeId = 3,
                            Order = 13,
                            Unit = "пФ",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 46,
                            Code = "PowerDissipation",
                            DisplayName = "Мощность рассеивания",
                            FormTypeId = 3,
                            Order = 14,
                            Unit = "мВт",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 47,
                            Code = "AmbientTemperatureCase",
                            DisplayName = "Температура корпуса",
                            FormTypeId = 3,
                            Order = 15,
                            Unit = "°C",
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 48,
                            Code = "PosName",
                            DisplayName = "Позиционное обозначение и номера выводов",
                            FormTypeId = 3,
                            Order = 16,
                            ValueKind = 4
                        },
                        new
                        {
                            Id = 49,
                            Code = "LoadKoeff",
                            DisplayName = "Коэффициент нагрузки",
                            FormTypeId = 3,
                            Order = 17,
                            ValueKind = 4
                        });
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pins")
                        .HasColumnType("TEXT");

                    b.Property<string>("StringValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentFamilyId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ParameterDefinitionId");

                    b.ToTable("ParameterValues", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Component", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.ComponentFamily", "ComponentFamily")
                        .WithMany("Components")
                        .HasForeignKey("ComponentFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentFamily");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterDefinition", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.FormType", "FormType")
                        .WithMany("Parameters")
                        .HasForeignKey("FormTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormType");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterValue", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.ComponentFamily", "ComponentFamily")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ComponentFamilyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectronicMaps.Domain.Entities.Component", "Component")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectronicMaps.Domain.Entities.ParameterDefinition", "ParameterDefinition")
                        .WithMany()
                        .HasForeignKey("ParameterDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("ComponentFamily");

                    b.Navigation("ParameterDefinition");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Component", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamily", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.FormType", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
