// <auto-generated />
using System;
using ElectronicMaps.Infrastructure.Persistence.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicMaps.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110214157_AddParameterValueRemark")]
    partial class AddParameterValueRemark
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindowsIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WindowsIdentity")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerificationNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerifiedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ComponentFamilyId");

                    b.HasIndex("FormTypeId");

                    b.HasIndex("VerificationStatus");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyFormTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerificationNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerifiedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("FamilyFormTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("VerificationStatus");

                    b.ToTable("ComponentFamilies", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.FormType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FormTypes", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FormTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationPattern")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormTypeId");

                    b.HasIndex("FormTypeId", "Code")
                        .IsUnique();

                    b.ToTable("ParameterDefinitions", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("double precision");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParameterDefinitionId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pins")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StringValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParameterDefinitionId");

                    b.HasIndex("ParameterDefinitionId1");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("ComponentFamilyId", "ParameterDefinitionId")
                        .IsUnique()
                        .HasFilter("\"ComponentFamilyId\" IS NOT NULL");

                    b.HasIndex("ComponentId", "ParameterDefinitionId")
                        .IsUnique()
                        .HasFilter("\"ComponentId\" IS NOT NULL");

                    b.ToTable("ParameterValues", null, t =>
                        {
                            t.HasCheckConstraint("CK_ParameterValues_Target", "((\"ComponentId\" IS NOT NULL AND \"ComponentFamilyId\" IS NULL) OR (\"ComponentId\" IS NULL AND \"ComponentFamilyId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterValueRemark", b =>
                {
                    b.Property<int>("ParameterValueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemarkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParameterValueId", "RemarkId");

                    b.HasIndex("RemarkId");

                    b.ToTable("ParameterValueRemarks", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Remark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("Remarks", (string)null);
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Component", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.ComponentFamily", "ComponentFamily")
                        .WithMany("Components")
                        .HasForeignKey("ComponentFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicMaps.Domain.Entities.FormType", "FormType")
                        .WithMany()
                        .HasForeignKey("FormTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectronicMaps.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ComponentFamily");

                    b.Navigation("FormType");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamily", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.FormType", "FamilyFormType")
                        .WithMany()
                        .HasForeignKey("FamilyFormTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamilyFormType");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterDefinition", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.FormType", "FormType")
                        .WithMany("Parameters")
                        .HasForeignKey("FormTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormType");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterValue", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.ComponentFamily", "ComponentFamily")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ComponentFamilyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectronicMaps.Domain.Entities.Component", "Component")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectronicMaps.Domain.Entities.ParameterDefinition", "ParameterDefinition")
                        .WithMany()
                        .HasForeignKey("ParameterDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicMaps.Domain.Entities.ParameterDefinition", null)
                        .WithMany("ParameterValues")
                        .HasForeignKey("ParameterDefinitionId1");

                    b.HasOne("ElectronicMaps.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Component");

                    b.Navigation("ComponentFamily");

                    b.Navigation("ParameterDefinition");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterValueRemark", b =>
                {
                    b.HasOne("ElectronicMaps.Domain.Entities.ParameterValue", "ParameterValue")
                        .WithMany("Remarks")
                        .HasForeignKey("ParameterValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicMaps.Domain.Entities.Remark", "Remark")
                        .WithMany("ParameterValues")
                        .HasForeignKey("RemarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParameterValue");

                    b.Navigation("Remark");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Component", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ComponentFamily", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.FormType", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterDefinition", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.ParameterValue", b =>
                {
                    b.Navigation("Remarks");
                });

            modelBuilder.Entity("ElectronicMaps.Domain.Entities.Remark", b =>
                {
                    b.Navigation("ParameterValues");
                });
#pragma warning restore 612, 618
        }
    }
}
